# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Default
variables:
  python.version: '3.7'
  threads: '3'
  server: 'BENDER'
  executor: 'LOCAL'
  browser: 'CHROME'
  config: 'config.json'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: $(python.version)
    addToPath: true 
    
- script: 'python -m pip install --upgrade pip && pip install -r requirements.txt'
  displayName: 'Install dependencies'

- script: 'pip install pytest && py.test tests --tx $(threads)*popen --dist=load --alluredir=allure_results --server=$(server) --params=$(config) --executor=$(executor) --browser=$(browser)'
  displayName: pytest

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/allure-results'
  inputs:
    testResultsFiles: '**/allure-results'
    testRunTitle: 'Python $(python.version)'

