# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'
variables:
  python.version: '3.7'
 
steps:

- script: 'sudo apt-add-repository ppa:qameta/allure'
- script: 'sudo apt-get update' 
- script: 'sudo apt-get install allure'

- task: UsePythonVersion@0
  inputs:
    versionSpec: $(python.version)
    addToPath: true      
    
- script: 'python -m pip install --upgrade pip && pip install -r requirements.txt'
  displayName: 'Install dependencies'

- script: 'py.test -o junit_family=xunit2 --junitxml=test-results.xml --alluredir=allure-results tests'
  continueOnError: true 
  displayName: 'Run tests'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'test-results.xml'
    testRunTitle: 'my_test_results'        
    publishRunAttachments: true
  displayName: 'Publish as Junit'
    
- task: ivang7.allure-test-reports.allure-generate.AllureGenerate@1
  continueOnError: true 
  inputs:
    resultsDir: 'allure-results'
    targetDir: 'allure-report/$(Build.BuildNumber)'
  displayName: 'Generate Allure Report'

