# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
    vmImage: 'ubuntu-16.04'
variables:
  python.version: '3.7'
 
steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: $(python.version)
    addToPath: true     

- script: 'ls -la'
  displayName: 'Show al files'    
    
- script: 'python -m pip install --upgrade pip && pip install -r requirements.txt'
  displayName: 'Install dependencies'

- script: 'py.test -o junit_family=xunit2 --junitxml=test-results.xml --alluredir=allure-results tests'
  continueOnError: true 
  displayName: 'Run tests'
 
- script: 'ls -la'
  displayName: 'Show al files'

- script: 'allure serve allure-results'
  continueOnError: true
  displayName: 'Some allure shit'

#- task: PublishTestResults@2
#  displayName: 'Publish Test Results **/allure-results'
#  inputs:
#    testResultsFiles: '**/allure-results'
#    testRunTitle: 'Python $(python.version)'
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'test-results.xml'

