version: '3'

volumes:
  allure-docker-service:
    driver: local

services:
  allure-docker-service:
    build:
      context: ../1/s
      dockerfile: docker-custom/Dockerfile.bionic-custom
      args:
        ALLURE_RELEASE: "2.13.5"
    environment:
      DEV_MODE: 0
      CHECK_RESULTS_EVERY_SECONDS: NONE
      KEEP_HISTORY: 1
      KEEP_HISTORY_LATEST: 5
      #URL_PREFIX: "/my-prefix"
      SECURITY_USER: "my_username"
      SECURITY_PASS: "my_password"
      SECURITY_ENABLED: 0
    ports:
      - "5050:5050"
    volumes:
      - ./allure-results:/app/allure-results

  allure-ui:
    image: "frankescobar/allure-docker-service-ui"
    environment:
      ALLURE_DOCKER_PUBLIC_API_URL: "http://localhost:5050"
      ALLURE_DOCKER_PUBLIC_API_URL_PREFIX: ""
    ports:
      - "7474:5252"
