version: '3'

volumes:
  allure-docker-service:
    driver: local

services:
  allure:
    image: "frankescobar/allure-docker-service"
    environment:
      DEV_MODE: 0
      CHECK_RESULTS_EVERY_SECONDS: NONE
      KEEP_HISTORY: 1
      KEEP_HISTORY_LATEST: 25
      #URL_PREFIX: "/my-prefix"
      SECURITY_USER: "ver"
      SECURITY_PASS: "ver"
      SECURITY_ENABLED: 0
    ports:
      - "5050:5050"
    volumes:
      - ./projects:/app/projects

  allure-ui:
    image: "frankescobar/allure-docker-service-ui"
    environment:
      ALLURE_DOCKER_PUBLIC_API_URL: "http://localhost:5050"
      ALLURE_DOCKER_PUBLIC_API_URL_PREFIX: ""
    ports:
      - "7474:5252"
